export const UPDATE_ACTIVE_NODE = 'UPDATE_ACTIVE_NODE'
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'
export const GET_CATEGORY_DATA_ERROR = 'GET_CATEGORY_DATA_ERROR'
export const GET_CATEGORY_DATA_LOADING = 'GET_CATEGORY_DATA_LOADING'

export const SET_LOGIN_RESPONSE = 'SET_LOGIN_RESPONSE'
export const SET_LOGIN_RESPONSE_ERROR = 'SET_LOGIN_RESPONSE_ERROR'
export const SET_LOGIN_RESPONSE_LOADING = 'SET_LOGIN_RESPONSE_LOADING'
export const POST_USER_DATA_ERROR = 'POST_USER_DATA_ERROR'
export const POST_USER_DATA_LOADING = 'POST_USER_DATA_LOADING'
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS'
export const OPEN_DIALOG_MODAL = 'OPEN_DIALOG_MODAL'
export const CLOSE_DIALOG_MODAL = 'CLOSE_DIALOG_MODAL'
export const POST_ITEM_DATA = 'POST_ITEM_DATA'
export const POST_ITEM_DATA_ERROR = 'POST_ITEM_DATA_ERROR'
export const POST_ITEM_DATA_LOADING = 'POST_ITEM_DATA_LOADING'
export const GET_CHILD_ENTITY = 'GET_CHILD_ENTITY'
export const GET_CHILD_ENTITY_LOADING = 'GET_CHILD_ENTITY_LOADING'
export const GET_CHILD_ENTITY_ERROR = 'GET_CHILD_ENTITY_ERROR'
export const GET_STATE_DATA = 'GET_STATE_DATA'
export const GET_BRAND_DATA = 'GET_BRAND_DATA'

export const GET_BRAND_DATA_ERROR = 'GET_BRAND_DATA_ERROR'
export const GET_STATE_DATA_ERROR = 'GET_STATE_DATA_ERROR'

export const POST_BRAND_DATA = 'POST_BRAND_DATA'
export const POST_BRAND_DATA_ERROR = 'POST_BRAND_DATA_ERROR'
export const POST_BRAND_DATA_LOADING = 'POST_BRAND_DATA_LOADING'
export const GET_ALL_USERS = 'GET_sLL_USERS'
export const GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'


export const DELETE_ITEM_DATA_ERROR = 'DELETE_ITEM_DATA_ERROR'
export const DELETE_ITEM_DATA_LOADING = 'DELETE_ITEM_DATA_LOADING'
export const DELETE_ITEM_DATA = 'DELETE_ITEM_DATA'

export const ADD_EDIT_ITEM_DATA = 'ADD_EDIT_ITEM_DATA'

export const SET_USER_NOT_AUTH = 'SET_USER_NOT_AUTH'




